
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RESERVED = 6;
  public static final int STRING_LITERAL = 10;
  public static final int FUNCTION = 29;
  public static final int CONST = 23;
  public static final int CHAR = 22;
  public static final int CHAR_LITERAL = 11;
  public static final int FLOATING_POINT_NUMERIC_LITERAL = 7;
  public static final int OTHER = 15;
  public static final int MINUSOP = 50;
  public static final int CASE = 21;
  public static final int ERROR_STRING = 56;
  public static final int SEMI = 48;
  public static final int REPEAT = 36;
  public static final int INT = 31;
  public static final int ARRAY = 18;
  public static final int FOR = 28;
  public static final int WRITE = 45;
  public static final int ERROR_COMMENT = 52;
  public static final int ERROR_INTEGER = 55;
  public static final int ERROR_IDENTIFIER = 54;
  public static final int COMMA = 49;
  public static final int BEGIN = 19;
  public static final int UNTIL = 42;
  public static final int IF = 30;
  public static final int ID = 59;
  public static final int NUMERIC_CHAR_LITERAL = 12;
  public static final int OF = 33;
  public static final int EOF = 0;
  public static final int BOOLEAN = 20;
  public static final int EQUAL = 46;
  public static final int SCIENTIFIC_NOTATION_NUMERIC_LITERAL = 9;
  public static final int TRUE = 41;
  public static final int error = 1;
  public static final int PROGRAM = 17;
  public static final int ERROR_FLOATING_POINT = 53;
  public static final int MINUS_OP = 16;
  public static final int OPEN_PARENTHESIS = 13;
  public static final int COLON = 51;
  public static final int LITERAL = 47;
  public static final int SHORTINT = 37;
  public static final int ELSE = 25;
  public static final int BOOLEAN_OPERATOR = 3;
  public static final int READ = 35;
  public static final int TO = 40;
  public static final int WHILE = 44;
  public static final int ERROR_INVALID_LENGTH = 58;
  public static final int INTEGER_NUMERIC_LITERAL = 8;
  public static final int THEN = 39;
  public static final int ARITHMETICOP = 5;
  public static final int END = 26;
  public static final int STRING = 38;
  public static final int CLOSE_PARENTHESIS = 14;
  public static final int OPERATOR = 4;
  public static final int ERROR_INVALID_CHARACTER = 57;
  public static final int FALSE = 27;
  public static final int VAR = 43;
  public static final int LONGINT = 32;
  public static final int PROCEDURE = 34;
  public static final int DO = 24;
  public static final int IDENTIFIER = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "BOOLEAN_OPERATOR",
  "OPERATOR",
  "ARITHMETICOP",
  "RESERVED",
  "FLOATING_POINT_NUMERIC_LITERAL",
  "INTEGER_NUMERIC_LITERAL",
  "SCIENTIFIC_NOTATION_NUMERIC_LITERAL",
  "STRING_LITERAL",
  "CHAR_LITERAL",
  "NUMERIC_CHAR_LITERAL",
  "OPEN_PARENTHESIS",
  "CLOSE_PARENTHESIS",
  "OTHER",
  "MINUS_OP",
  "PROGRAM",
  "ARRAY",
  "BEGIN",
  "BOOLEAN",
  "CASE",
  "CHAR",
  "CONST",
  "DO",
  "ELSE",
  "END",
  "FALSE",
  "FOR",
  "FUNCTION",
  "IF",
  "INT",
  "LONGINT",
  "OF",
  "PROCEDURE",
  "READ",
  "REPEAT",
  "SHORTINT",
  "STRING",
  "THEN",
  "TO",
  "TRUE",
  "UNTIL",
  "VAR",
  "WHILE",
  "WRITE",
  "EQUAL",
  "LITERAL",
  "SEMI",
  "COMMA",
  "MINUSOP",
  "COLON",
  "ERROR_COMMENT",
  "ERROR_FLOATING_POINT",
  "ERROR_IDENTIFIER",
  "ERROR_INTEGER",
  "ERROR_STRING",
  "ERROR_INVALID_CHARACTER",
  "ERROR_INVALID_LENGTH",
  "ID"
  };
}

